### ISSUE TITLE
Intel Graphics (i915) driver for ogon-xserver

### ISSUE THREAD

**Issue by yefimg** [ogon-project/ogon-project#15]
Would it be possible to use existing Intel Integrated GPU to accelerate performance of the X Desktop environment?

It looks, like /opt/ogon/bin/ogon-backend-x does not have intel driver integrated and the system Xorg driver is not being used.

Thanks!

**Comment by hardening** [comment]
Your request is not that clear, do you mean using render nodes ?

**Comment by yefimg** [comment]
Sorry for being obscure.

We are passing Intel Integrated GPU (driver i915) via VFIO to the virtual machine running ogon-rdp-server. The goal is to have Xorg use the intel GPU driver for providing Xrender to the applications, for example Firefox and Chrome.
