### ISSUE TITLE
Missing /tmp/.X11-unix/X100 file

### ISSUE THREAD

**Issue by linuxrrze** [ogon-project/ogon-project#20]
After upgrading some machines from Ubuntu 18.04 (Bionic) to 20.04 (Focal) some ogon features got lost:

- X-forwarding no longer possible
- no re-connections possible

Hints:
- there's no /tmp/X11-unix/X100 file on the Focal (20.04) system
- /tmp/.pipe/ogon_100_X11 is missing

Packages for Ubuntu 18.04 and 20.04 are build from exactly the same sources, with the same debian/ settings.

Any idea what causes this?

**Comment by bmiklautz** [comment]
@linuxrrze do you use systemd services for ogon? If you do please check if `PrivateTmp` is disabled for the units. I think it's default on on 20.04.

**Comment by linuxrrze** [comment]
@bmiklautz yes, I'm using systemd services to start ogon-rdp-server and ogon-session-manager. I added option "PrivateTmp=no" to both files [Service] section: but still no such file.

Update: Also tried with services ogon-rdp-server and ogon-session-manager started without systemd .service files -> same result

**Comment by bmiklautz** [comment]
@linuxrrze I've I was able to pin down the problem. My suspicion that it is systemd related was wrong. It's a bug in the x11 backend that only surfaces on very recent Ubuntu versions.

**Comment by linuxrrze** [comment]
@bmiklautz  Thanks for the quick analysis! Let me know if there's something I can do to narrow down the problem / some patches to test.

Update: Applied your suggested fix "replace the exit() calls to _exit() in hw/xogon/rdpUpdate.c function system_background".
First tests look promising: No crash, missing files are back, X-Forwarding works.
Great!

**Comment by bmiklautz** [comment]
@linuxrrze ogon-project/xserver-ogon#7 should fix the problem.
