### ISSUE TITLE
clipboard sync working only in one direction

### ISSUE THREAD

**Issue by Glokeru** [ogon-project/ogon-project#21]
Hi, ive noticed that the clipboard sync works only in one direction: if i select something on the server and copy it, i can paste it on the client. Copying something on the client and pasting on the rdp-server doesnt work.
The server is a Ubuntu 18.04 machine. On the client side i tested with the Windows Default Client and Remmina on Ubuntu.
Any ideas what causes this? Can someone reproduce this behaviour?

**Comment by nfedera** [comment]
It depends on how you launch `rdpclip` in the session:  
If neither `--clipboard` nor `--primary` is specified the default mode is primary.  
In other words, depending on that mode, data gets pasted via "middle click" or "ctrl+v".

**Comment by nfedera** [comment]
@Glokeru any news ?

**Comment by Glokeru** [comment]
Hey there! The solution via "middle click" worked for me. I´ve kept the issue open because i wanted to test the mentioned rdpclip settings but didn´t find time till now.  Thanks for the solution and sorry for my inactivity.
