### ISSUE TITLE
Audio broken with Windows 10 mstsc, left/right channels switched

### ISSUE THREAD

**Issue by nfedera** [ogon-project/ogon-project#5]
We need:
- https://github.com/ogon-project/pulseaudio-ogon/pull/2
- https://github.com/FreeRDP/FreeRDP/pull/4989

Note: Responsible for the mixed up left/right channels is an error in freerdp's wave2 pdu:
https://github.com/FreeRDP/FreeRDP/pull/4989/files#diff-4ede9284fc28e5fe8bd9fd960a4f1d83R511

**Comment by bmiklautz** [comment]
@nfedera nice finding!

**Comment by bmiklautz** [comment]
ogon-project/freerdp-ogon#2 contains the latest upstream fixes.
