### ISSUE TITLE
Dynamic channel behaviour

### ISSUE THREAD

**Issue by hardening** [ogon-project/ogon-project#9]
I've noticed that if we don't explicitly close a dynamic channel, we don't send a `DVC close` message. This is really unfortunate because for example if the server application using channels crash or doesn't quit cleanly, the client channel is not notified of that, and so can't take appropriate cleanup actions.

I guess it would be nicer if the close message was send as soon as we disconnect from the channel's pipe. I'm even wondering why we accept more than one connection on the channel's pipe...

**Comment by hardening** [comment]
I can confirm that the close message is sent on windows. When the application closes the channel or at application death (unclean cleanup case).

**Comment by nfedera** [comment]
@hardening the following patch seems to fix that issue for me. please confirm:

```diff
diff --git a/rdp-server/channels.c b/rdp-server/channels.c
index dba06a12..a78529d3 100644
--- a/rdp-server/channels.c
+++ b/rdp-server/channels.c
@@ -48,6 +48,8 @@ static void ringbuffer_reset(RingBuffer *rb) {
        ringbuffer_commit_read_bytes(rb, ringbuffer_used(rb));
 }

+static BOOL dvc_send_close(registered_virtual_channel *dvc);
+
 registered_virtual_channel *VirtualChannelManagerGetChannelByNameAndType(ogon_vcm *vcm,
        const char *name, UINT16 type)
 {
@@ -998,9 +1000,14 @@ static int handle_vc_named_pipe_event(int mask, int fd, HANDLE handle, void *dat


 out_shutdown:
-       vc_disconnect_client_part(channel);
+       virtual_manager_close_dynamic_virtual_channel_common(channel);
+       if (channel->channel_type == RDP_PEER_CHANNEL_TYPE_DVC) {
+               if (!dvc_send_close(channel)) {
+                       WLog_ERR(TAG, "error while sending close in DVC");
+               }
+       }
+       vc_free(channel);
        return -1;
-
 }

```

**Comment by hardening** [comment]
@nfedera works for me too
